### PR TITLE
Do not count "sea_floor_depth" as a vertical coordinate

### LINKED ISSUE #25: "sea_floor_depth_below_X" is not a vertical coordinate
The util function `vertical_coordinate_type()` correctly exempts variables with standard_name "sea_floor_depth_below_sea_surface" from being regarded as a vertical coordinate. However, there are several other variants on this standard_name (e.g. "sea_floor_depth_below_mean_sea_level"), which should equally be exempt. The exemption (line [107](https://github.com/aodn/cc-plugin-imos/blob/master/cc_plugin_imos/util.py#L107)) should be broadened to any standard name starting with "sea_floor_depth" (including this exact string).

### PR DESCRIPTION
**Pull request by mhidas**
Fixes #25

### CODE REVIEW

**Review by bpasquer — APPROVED** [review]
Happy with that  👍

**Comment by mhidas** [comment]
@bpasquer This is now ready to test in RC, if you want to check that it out.

**Comment by bpasquer** [comment]
Thanks @mhidas 
@lbesnard can you text on RC with the checks back on, pls

**Comment by lbesnard** [comment]
all good

**Pull request merged**
