### PR TITLE
Fix unittests

### PR DESCRIPTION
**Pull request by mhidas**
Two minor fixes that will allow the unittests to pass with the latest version of the python netCDF4 package.

### CODE REVIEW

**Comment by ghost** [comment]
@mhidas I added netcdf-bin to travis, but it's still failing with:

```
ncgen: NetCDF: Not a valid data type or _FillValue type mismatch
	(genbin.c:163)
```

Anything else missing?

**Comment by mhidas** [comment]
@lwgordonimos Can we get Travis to use a newer version of the netcdf-bin package? It's using 4.1.3. I have 4.4.0 and it works fine.

For that matter, why is it on `trusty`? Can we request a `xenial` machine?

**Comment by mhidas** [comment]
I can't easily go back to earlier versions, but at least libnetcdf 4.2.1.1 is needed for ncgen to generate those test files without complaining.

**Review by ggalibert — APPROVED** [review]
Python stuff looks good to me.

**Pull request merged**
